stages:
- build
- test

build:
  image: gcc
  stage: build
  script: make -f runtime/south/platform/x86/Makefile CONFIG="runtime/south/platform/x86/cc_config_x86_test.h"
  artifacts:
    paths:
      - calvin_c

test:
  image: python:2.7
  stage: test
  script: ./test/test.sh no


